### ISSUE TITLE
Fehler bei Bildkonvertierung

### ISSUE THREAD

**Issue by bbuehlmann** [4teamwork/docxmerge#1]
https://spv.onegovgever.ch/sitzungen/committee-7/meeting-37/view

Traceback (most recent call last):
  File "/home/zope/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/Publish.py", line 138, in publish
    request, bind=1)
  File "/home/zope/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/mapply.py", line 77, in mapply
    if debug is not None: return debug(object,args,context)
  File "/home/zope/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/Publish.py", line 48, in call_object
    result=apply(object,args) # Type s to step into published object.
  File "/home/zope/theta.4teamwork.ch/55-spv.onegovgever.ch/src/opengever.core/opengever/meeting/browser/protocol.py", line 36, in __call__
    command.execute()
  File "/home/zope/theta.4teamwork.ch/55-spv.onegovgever.ch/src/opengever.core/opengever/meeting/command.py", line 272, in execute
    return self.update_protocol_document()
  File "/home/zope/theta.4teamwork.ch/55-spv.onegovgever.ch/src/opengever.core/opengever/meeting/command.py", line 288, in update_protocol_document
    document.file.data = self.generate_file_data()
  File "/home/zope/theta.4teamwork.ch/55-spv.onegovgever.ch/src/opengever.core/opengever/meeting/command.py", line 330, in generate_file_data
    builder.append(Document(proposal_path))
  File "/home/zope/theta.4teamwork.ch/55-spv.onegovgever.ch/src/docxmerge/docxmerge/builder.py", line 46, in append
    self.add_images(doc, element)
  File "/home/zope/theta.4teamwork.ch/55-spv.onegovgever.ch/src/docxmerge/docxmerge/builder.py", line 81, in add_images
    StringIO(img_part._blob))
  File "/home/zope/eggs/python_docx-0.8.6-py2.7.egg/docx/package.py", line 76, in get_or_add_image_part
    image = Image.from_file(image_descriptor)
  File "/home/zope/eggs/python_docx-0.8.6-py2.7.egg/docx/image/image.py", line 55, in from_file
    return cls._from_stream(stream, blob, filename)
  File "/home/zope/eggs/python_docx-0.8.6-py2.7.egg/docx/image/image.py", line 176, in _from_stream
    image_header = _ImageHeaderFactory(stream)
  File "/home/zope/eggs/python_docx-0.8.6-py2.7.egg/docx/image/image.py", line 198, in _ImageHeaderFactory
    return cls.from_stream(stream)
  File "/home/zope/eggs/python_docx-0.8.6-py2.7.egg/docx/image/jpeg.py", line 68, in from_stream
    markers = _JfifMarkers.from_stream(stream)
  File "/home/zope/eggs/python_docx-0.8.6-py2.7.egg/docx/image/jpeg.py", line 111, in from_stream
    for marker in marker_parser.iter_markers():
  File "/home/zope/eggs/python_docx-0.8.6-py2.7.egg/docx/image/jpeg.py", line 177, in iter_markers
    marker_code, self._stream, segment_offset
  File "/home/zope/eggs/python_docx-0.8.6-py2.7.egg/docx/image/jpeg.py", line 271, in _MarkerFactory
    return marker_cls.from_stream(stream, marker_code, offset)
  File "/home/zope/eggs/python_docx-0.8.6-py2.7.egg/docx/image/jpeg.py", line 413, in from_stream
    tiff = cls._tiff_from_exif_segment(stream, offset, segment_length)
  File "/home/zope/eggs/python_docx-0.8.6-py2.7.egg/docx/image/jpeg.py", line 455, in _tiff_from_exif_segment
    return Tiff.from_stream(substream)
  File "/home/zope/eggs/python_docx-0.8.6-py2.7.egg/docx/image/tiff.py", line 36, in from_stream
    parser = _TiffParser.parse(stream)
  File "/home/zope/eggs/python_docx-0.8.6-py2.7.egg/docx/image/tiff.py", line 63, in parse
    ifd_entries = _IfdEntries.from_stream(stream_rdr, ifd0_offset)
  File "/home/zope/eggs/python_docx-0.8.6-py2.7.egg/docx/image/tiff.py", line 176, in from_stream
    entries = dict((e.tag, e.value) for e in ifd_parser.iter_entries())
  File "/home/zope/eggs/python_docx-0.8.6-py2.7.egg/docx/image/tiff.py", line 176, in 
    entries = dict((e.tag, e.value) for e in ifd_parser.iter_entries())
  File "/home/zope/eggs/python_docx-0.8.6-py2.7.egg/docx/image/tiff.py", line 204, in iter_entries
    ifd_entry = _IfdEntryFactory(self._stream_rdr, dir_entry_offset)
  File "/home/zope/eggs/python_docx-0.8.6-py2.7.egg/docx/image/tiff.py", line 231, in _IfdEntryFactory
    return entry_cls.from_stream(stream_rdr, offset)
  File "/home/zope/eggs/python_docx-0.8.6-py2.7.egg/docx/image/tiff.py", line 256, in from_stream
    stream_rdr, offset, value_count, value_offset
  File "/home/zope/eggs/python_docx-0.8.6-py2.7.egg/docx/image/tiff.py", line 294, in _parse_value
    return stream_rdr.read_str(value_count-1, value_offset)
  File "/home/zope/eggs/python_docx-0.8.6-py2.7.egg/docx/image/helpers.py", line 70, in read_str
    chars = self._unpack_item(struct, base, offset)
  File "/home/zope/eggs/python_docx-0.8.6-py2.7.egg/docx/image/helpers.py", line 96, in _unpack_item
    bytes_ = self._read_bytes(struct.size, base, offset)
  File "/home/zope/eggs/python_docx-0.8.6-py2.7.egg/docx/image/helpers.py", line 88, in _read_bytes
    raise UnexpectedEndOfFileError
UnexpectedEndOfFileError

**Comment by buchi** [comment]
Fixed in 788605df923b718831dc9bd4065626c5d8c41690

**Comment by bbuehlmann** [comment]
:+1:
